### ISSUE TITLE
PyQt bindings doesn't work correctly.

### ISSUE THREAD

**Issue by Reverier-Xu** [githubuser0xFFFF/Qt-Advanced-Docking-System#191]
```
/usr/bin/python3.8 test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from PyQtAds.QtAds import *
  File "/usr/lib/python3.8/site-packages/PyQtAds-3.4.2-py3.8-linux-x86_64.egg/PyQtAds/QtAds/__init__.py", line 1, in <module>
    from .ads import ads
ImportError: /usr/lib/python3.8/site-packages/PyQtAds-3.4.2-py3.8-linux-x86_64.egg/PyQtAds/QtAds/ads.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTVN3ads15CTitleBarButtonE

Process finished with exit code 1
```

test.py:

```
import sys

from PyQt5 import QtWidgets, QtGui, QtCore
from PyQtAds.QtAds import *


class UI_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None, flags=None):
        super(UI_MainWindow, self).__init__(parent=parent, flags=None)
        central = DockManager()
        self.setCentralWidget(central)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = UI_MainWindow()
    window.show()
    app._exec()
```

**Comment by hhslepicka** [comment]
@githubuser0xFFFF I will get it done either tonight or by tomorrow close of day.

**Comment by githubuser0xFFFF** [comment]
Thank you very much for your kind support :blush:. I think I will add a Python section on the project homepage where I will credit the Python contributors.
