### ISSUE TITLE
pip install PyQtAds Error

### ISSUE THREAD

**Issue by Zholtikov** [githubuser0xFFFF/Qt-Advanced-Docking-System#434]
When use `pip install PyQtAds Error` take error:

```
Collecting PyQtAds
  Using cached PyQtAds-3.8.1.tar.gz (10.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [27 lines of output]
  Traceback (most recent call last):
    File "D:\PycharmProjects\pythonProject3_test_ads\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
      hook = backend.prepare_metadata_for_build_wheel
  AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "D:\PycharmProjects\pythonProject3_test_ads\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "D:\PycharmProjects\pythonProject3_test_ads\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\PycharmProjects\pythonProject3_test_ads\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "C:\Users\vladi\AppData\Local\Temp\pip-build-env-dgjvr_6b\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
      project = AbstractProject.bootstrap('wheel',
    File "C:\Users\vladi\AppData\Local\Temp\pip-build-env-dgjvr_6b\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
      project.setup(pyproject, tool, tool_description)
    File "C:\Users\vladi\AppData\Local\Temp\pip-build-env-dgjvr_6b\overlay\Lib\site-packages\sipbuild\project.py", line 584, in setup
      self.apply_user_defaults(tool)
    File "C:\Users\vladi\AppData\Local\Temp\pip-build-env-dgjvr_6b\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "C:\Users\vladi\AppData\Local\Temp\pip-build-env-dgjvr_6b\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
      self.builder.apply_user_defaults(tool)
    File "C:\Users\vladi\AppData\Local\Temp\pip-build-env-dgjvr_6b\overlay\Lib\site-packages\pyqtbuild\builder.py", line 67, in apply_user_defaults
      raise PyProjectOptionException('qmake',
  sipbuild.pyproject.PyProjectOptionException
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If dependencies are the problem then why doesn't it install and check itself...

What is the cause of this problem?  (python 3.`10)

https://pypi.org/project/PyQtAds/3.8.1/

**Comment by githubuser0xFFFF** [comment]
ADS Python support is a third party contribution so I'm not able to fix this. Maybe some contributor of the Python code can step in.

**Comment by Zholtikov** [comment]
The problem is in the outdated version of pyqt5-sip, pyqtads requires sip v4 while now version is v12 . I see that you have a pull request related to this - when will it be accepted?

> ADS Python support is a third party contribution so I'm not able to fix this. Maybe some contributor of the Python code can step in.

**Comment by githubuser0xFFFF** [comment]
If I get the information that it is ready
